filter:
  max_price: 500.0
  min_volume: 500000
  generated_at: '2026-09-20T14:23:06.182140'
symbols:
- AMBUJACEM
- ASHOKLEY
- BANKBARODA
- BEL
- BPCL
- CANBK
- COALINDIA
- DABUR
- GAIL
- ICICIPRULI
- IDFCFIRSTB
- IOC
- ITC
- JIOFIN
- KOTAKBANK
- LICI
- MOTHERSON
- NTPC
- ONGC
- PFC
- PNB
- POWERGRID
- RECLTD
- TATAPOWER
- TATASTEEL
- VEDL
- WIPRO
